### ISSUE TITLE
Ready the repository for npm publishing

### ISSUE THREAD

**Issue by joepavitt** [flowforge/forge-ui-components#1]
Ensure we have the relevant criteria in place, and code stability, in order to release the project to npm.

### Acceptance Criteria

Full criteria as per [handbook](https://flowforge.com/handbook/development/packaging/):

### Naming
- [x] GitHub convention (flowforge-ui-components)
- [x] npm convention (`@flowforge/flowforge-ui-components`)

### Content
- [x] README.md
- [x] LICENSE

### Linting
- [x] `.eslintrc`

### Workflow
- [x] GitHub Project Automation Workflow

### package.json
- [x] description
- [x] repository
- [x] homepage
- [x] bugs
- [x] license
- [x] author
- [x] engines

**Comment by joepavitt** [comment]
@knolleary not sure if/where I can be opening a formal PR for this? Or is a review (with your comments) okay to include in this thread?

**Comment by knolleary** [comment]
All looks good aside from one thing... naming.

To be fully consistent, the package name should be `@flowforge/forge-ui-components`

**Comment by knolleary** [comment]
I think this is good to close now?
